# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-18 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtoken',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
