# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-30 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_registrationtoken_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='members',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
